#!/usr/bin/env python3
"""Generate report/RESULTS.md from saved criterion runs.

Reads the slope point-estimate (the value criterion prints on its `time:` line)
for each benchmark from the three result trees, then writes environment info and
comparison tables. Run the benches first:

    npm run bench:native && npm run bench:d8 && npm run bench:wasmtime

This script only reads what those runs saved; it does not run anything itself.
"""

import os
import sys
import platform
import subprocess
import shutil
import json
import hashlib

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

RUNTIMES = {
    "native":   ROOT / "target" / "criterion",
    "d8":       ROOT / "target" / "d8" / "criterion",
    "wasmtime": ROOT / "target" / "wasmtime" / "criterion",
}

RUNTIME_TITLES = {
    "native": "Native",
    "d8": "V8 (d8)",
    "wasmtime": "wasmtime (Cranelift)",
}

BENCHES = [
    "udivrem128",
    "udiv128",
    "urem128",
    "sdivrem128",
    "sdiv128",
    "srem128",
    "divrem_loop_invariant",
]

IMPLS = ("reciprocal", "builtin")


def read_ns(root, impl, bench):
    """Slope (else mean) point-estimate in ns, or None when the run is missing."""
    path = root / f"{impl}_{bench}" / "new" / "estimates.json"
    if not path.is_file():
        return None

    data = json.loads(path.read_text(encoding="utf-8"))
    est  = data.get("slope") or data.get("mean")
    return est["point_estimate"] if est else None


def fmt_time(ns):
    if ns is None:
        return "-"
    if ns >= 1e6:
        return f"{ns / 1e6:.2f} ms"
    if ns >= 1e3:
        return f"{ns / 1e3:.2f} µs"
    return f"{ns:.2f} ns"


def rel_pct(a, b):
    """(a - b) / b as a signed percent, or '-' when either side is missing."""
    if a is None or b is None or b == 0:
        return "-"
    return f"{(a - b) / b * 100:+.1f}%"


def sh(cmd):
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=10).stdout.strip()
    except Exception:
        return ""


def wasmtime_bin():
    return shutil.which("wasmtime") or str(Path.home() / ".wasmtime" / "bin" / "wasmtime")


def v8_bin():
    return shutil.which("v8") or str(Path.home() / ".jsvu" / "bin" / "v8")


def environment():
    rows = []

    if platform.system() == "Darwin":
        rows.append(("CPU", sh(["sysctl", "-n", "machdep.cpu.brand_string"]) or platform.machine()))
        rows.append(("OS", f"macOS {sh(['sw_vers', '-productVersion'])} ({platform.machine()})"))
    else:
        rows.append(("CPU", platform.processor() or platform.machine()))
        rows.append(("OS", f"{platform.system()} {platform.release()} ({platform.machine()})"))

    rows.append(("Cores", str(os.cpu_count())))
    rows.append(("rustc", sh(["rustc", "--version"]) or "?"))
    rows.append(("d8", sh([v8_bin(), "-e", "print(version())"]) or "?"))
    rows.append(("wasmtime", sh([wasmtime_bin(), "--version"]) or "?"))

    return rows


def env_hash(rows):
    """Short hex fingerprint of CPU, OS and toolchain versions (rustc, d8, wasmtime)."""
    keys = ("CPU", "OS", "rustc", "d8", "wasmtime")
    env  = dict(rows)
    blob = "\n".join(f"{k}={env.get(k, '')}" for k in keys)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:8]


def md_table(header, rows, right_from=1):
    sep  = ["---:" if i >= right_from else "---" for i in range(len(header))]
    out  = ["| " + " | ".join(header) + " |", "| " + " | ".join(sep) + " |"]
    out += ["| " + " | ".join(r)      + " |" for r in rows]
    return "\n".join(out)


def build(env_rows):
    data = {
        rt: {im: {b: read_ns(root, im, b) for b in BENCHES} for im in IMPLS}
        for rt, root in RUNTIMES.items()
    }

    out = []

    out.append("# Benchmark results")

    out.append("")
    out.append("128-bit integer division: a reciprocal path (native u128 arithmetic that")
    out.append("lowers to the wide-arithmetic proposal) vs the `u128` / `i128` operators")
    out.append("(`__udivti3` / `__umodti3`), across native, V8 (d8) and wasmtime (Cranelift).")
    out.append("Generated by `scripts/report.py` from the saved criterion runs.")
    out.append("")

    out.append("## Environment")

    out.append("")
    out += [f"- **{k}**: {v}" for k, v in env_rows]
    out.append("")

    out.append("## Per-runtime: reciprocal vs builtin")

    out.append("")
    out.append("`rel = (reciprocal - builtin) / builtin`; negative means the reciprocal path")
    out.append("is faster. `builtin` is the native `u128` / `i128` operators.")
    out.append("")

    for rt in RUNTIMES:
        out.append(f"### {RUNTIME_TITLES[rt]}")
        out.append("")

        rows = []

        for b in BENCHES:
            blt = data[rt]["builtin"][b]
            rcp = data[rt]["reciprocal"][b]
            rows.append([f"`{b}`", fmt_time(blt), fmt_time(rcp), rel_pct(rcp, blt)])

        out.append(md_table(["bench", "builtin", "reciprocal", "rel"], rows))
        out.append("")

    out.append("## Cross-runtime: wasm cost vs native")
    out.append("")
    out.append("`% = (runtime - native) / native` for the same implementation; positive means")
    out.append("slower than running native.")
    out.append("")

    rows = []

    for b in BENCHES:
        nat_r = data["native"]["reciprocal"][b]
        nat_b = data["native"]["builtin"][b]
        rows.append([
            f"`{b}`",
            rel_pct(data["d8"]["reciprocal"][b], nat_r),
            rel_pct(data["wasmtime"]["reciprocal"][b], nat_r),
            rel_pct(data["d8"]["builtin"][b], nat_b),
            rel_pct(data["wasmtime"]["builtin"][b], nat_b),
        ])

    out.append(md_table(
        [
            "bench",
            "recip: d8",
            "recip: wasmtime",
            "builtin: d8",
            "builtin: wasmtime"
        ],
        rows,
    ))

    out.append("")
    return "\n".join(out)


def main():
    env_rows = environment()
    md = build(env_rows)
    hash = env_hash(env_rows)

    dest = ROOT / "report" / f"RESULTS-{hash}.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(md + "\n", encoding="utf-8")

    print(md)
    print(f"\nwritten to {dest.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
